# Message types: https://github.com/gazebosim/ros_gz/tree/humble/ros_gz_bridge

- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"

- topic_name: "odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"

- topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"

- ros_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_topic_name: "/world/downstairs/model/R2B2/joint_state"
  gz_type_name: "gz.msgs.Model"

- topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"